spring:
  mvc:
    static-path-pattern: /static/**
thymeleaf:
  cache: false
  prefix:  classpath:/templates/
  check-template-location: true
  suffix: .html
  encoding: utf-8
  mode: HTML
  datasource:
    url: jdbc:sqlserver://11.53.0.26:1433;DatabaseName=HospDataV9
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    data-username: sa
    data-password: sasasa
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      filters: stat,wall,slf4j

mybatis:
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8081
